version: '3'
services:
  endpoint:
    image: mintproject/fuseki-docker
    env_file:
      - .env
    ports:
      - 3030:3030
    volumes:
      - ./backups:/backups
      - databases:/fuseki-base/databases/

volumes:
  databases:
